// Mock properties
export const mockProperties = [
  {
    id: '1',
    title: 'Luxury Penthouse',
    slug: 'luxury-penthouse',
    price: 2500000,
    formattedPrice: '$2,500,000',
    beds: 4,
    baths: 3.5,
    sqft: 4200,
    type: 'Penthouse',
    status: 'buy',
    description: 'Stunning penthouse with city views.',
    shortDescription: 'Panoramic views from this 4-bed penthouse.',
    location: { address: '123 Main St', city: 'New York', state: 'NY', zipCode: '10001' },
    features: ['Pool', 'Gym', 'Concierge'],
    amenities: ['Rooftop', 'Parking'],
    images: [{ url: 'https://images.unsplash.com/photo-1600596542815-27b88e57e62f?w=800', isPrimary: true }],
    agentId: '1',
    agent_name: 'Alexander Sterling',
    yearBuilt: 2021,
    lotSize: null,
    virtualTourUrl: '',
    isFeatured: true,
    listingDate: '2025-01-15',
  },
  {
    id: '2',
    title: 'Beachfront Villa',
    slug: 'beachfront-villa',
    price: 35000,
    formattedPrice: '$35,000/mo',
    beds: 5,
    baths: 6,
    sqft: 5500,
    type: 'Villa',
    status: 'rent',
    description: 'Oceanfront villa with private beach.',
    location: { address: '456 Ocean Dr', city: 'Malibu', state: 'CA', zipCode: '90265' },
    features: ['Pool', 'Beach Access'],
    amenities: ['Spa', 'Guest House'],
    images: [{ url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800', isPrimary: true }],
    agentId: '1',
    agent_name: 'Alexander Sterling',
    yearBuilt: 2018,
    lotSize: 12600,
    isFeatured: true,
    listingDate: '2025-02-01',
  },
];

// Mock agents
export const mockAgents = [
  {
    id: '1',
    name: 'Alexander Sterling',
    title: 'Senior Broker',
    email: 'alex@primeestate.com',
    phone: '+1 (212) 555-0199',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400',
    bio: 'Over 15 years of luxury real estate experience.',
    specialty: ['Luxury Penthouses', 'New Developments'],
    languages: ['English', 'French'],
    licenseNumber: 'NY-12345',
    yearsExperience: 15,
    socialLinks: { instagram: '#', linkedin: '#' },
  },
  {
    id: '2',
    name: 'Elena Rostova',
    title: 'Director of New Developments',
    email: 'elena@primeestate.com',
    phone: '+1 (305) 555-0144',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
    bio: 'Specialist in pre-construction and architectural real estate.',
    specialty: ['Pre-construction', 'Waterfront'],
    languages: ['English', 'Russian'],
    licenseNumber: 'FL-67890',
    yearsExperience: 12,
    socialLinks: { instagram: '#', linkedin: '#' },
  },
];

// Mock inquiries
export const mockInquiries = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@example.com',
    phone: '(555) 123-4567',
    subject: 'Property Inquiry',
    message: 'Interested in the penthouse.',
    property: 'Luxury Penthouse',
    status: 'unread',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '(555) 987-6543',
    subject: 'Schedule Viewing',
    message: 'Would like to see the beach villa.',
    property: 'Beachfront Villa',
    status: 'read',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

// Mock stats
export const mockStats = {
  properties: 2,
  views: 1247,
  inquiries: 2,
  agents: 2,
  portfolio_value: 2535000,
};